services:
  be-core:
    image: ${CORE_IMAGE:-ghcr.io/fega-kt/backend-mikroorm-core:latest}
    restart: unless-stopped
    ports:
      - "2000:2000"
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
      CORE_PORT: 2000

  be-app:
    image: ${APP_IMAGE:-ghcr.io/fega-kt/backend-mikroorm-app:latest}
    restart: unless-stopped
    ports:
      - "2001:2001"
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
      APP_PORT: 2001

  be-core-jobs:
    image: ${CORE_JOBS_IMAGE:-ghcr.io/fega-kt/backend-mikroorm-core-jobs:latest}
    restart: unless-stopped
    ports:
      - "2002:2002"
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
      CORE_JOB_PORT: 2002

  be-app-jobs:
    image: ${APP_JOBS_IMAGE:-ghcr.io/fega-kt/backend-mikroorm-app-jobs:latest}
    restart: unless-stopped
    ports:
      - "2003:2003"
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_TOKEN: ${VAULT_TOKEN}
      APP_JOB_PORT: 2003
